### ISSUE TITLE
LED blinks green when power is taken from the grid

### ISSUE THREAD

**Issue by PA1RB** [SmartEVSE/Sensorbox-2#1]
According to the description in the [webshop](https://www.stegen.com/en/ev-products/129-smart-evse-sensorbox-v2.html):

> Furthermore, the Sensorbox has a status LED, which blinks orange when power is taken from the grid, or green when it feed back to the grid.

However, the LED blinks green in my case, I do not have solar panels (yet).
Grid consumtion reading on the connected SmartEVSE controller is correct.
Sensorbox is connected to the P1 port of the smart meter.

**Comment by mstegen** [comment]
If you use the P1 port of the smart meter, then the LED will always blink green, once every two seconds.

Only if you use CT's and the Voltage (mains) input, the LED will blink orange or green, three times (once for each phase) every two seconds.
Orange is power from the grid.
Green is power feed back to the grid.
