### ISSUE TITLE
Termination resistors on Modbus?

### ISSUE THREAD

**Issue by PA1RB** [SmartEVSE/Sensorbox-2#2]
The schematic of the SmartEVSE2 does not show termination resistors between A and B of the serial Modbus.

Distance between SmartEVSE and Sensorbox v2 in my case is appr. 50m and no problems in practice, but perhaps still a good idea to mount 100 Ohm termination resistors between A and B at both ends of the (Cat 5e) line?!

**Comment by webdotpulse** [comment]
It's always a good idea... But it has to be 120 ohm.
