### ISSUE TITLE
Compatability with Smart Meter Fluvius

### ISSUE THREAD

**Issue by dries007** [SmartEVSE/Sensorbox-2#4]
Hey, has this box been tested with the smart meters that Fluvius uses (in Flanders)?
There are 2 models: Sagemcom S211 single phase en T211-D three phase.
I have the thee phase model here, so I can provide you with real packets if you need them.

I suspect it would work, because on the website, it lists Sagemcom T210-D as compatible, and mentions DSMR 5. 
I know there is a small differance in the standards between NL and BE, namely that the current per phase is reported with 1 more didget of accuracy.

Thanks!

**Comment by mstegen** [comment]
Yes, the Sensorbox2 works with the Sagemcom T211-D, but only when using a 4 wire(3Phase+Neutral) Grid.

**Comment by dries007** [comment]
Thanks :)
