### ISSUE TITLE
Procedure for firmware upgrade

### ISSUE THREAD

**Issue by kennyschuoler** [SmartEVSE/Sensorbox-2#5]
Current hardware ( bought in november 2021 ): 
2x SmartEVSE v2.20 
1x Sensorbox v2 ( with P1 and micro usb port ) 
1x Waveshare RS232485 to ETH to read the modbus data ( which can then be used in Home Assistant to visualize )

I have compiled and uploaded the master branch version to our SmartEVSE's ( v2.30+)
At first glance everything is working, but after a short while i have noticed that both SmartEVSE gave a "no communication error" , meaning they are not receiving signals from the Sensorbox.

I was also adding the setup into Home Assistant and was mapping the Modbus addresses to be able to visualize, and in the near future configure the settings. At first sight it seems that there are overlapping modbus addresses between the current Sensorbox v2 and the SmartEVSE v2.30+ ( 0x0000 , ... ) which i think in this case will be the cause of my problem. ( Which is  just an assumption )
I have read that there was a rewrite of the modbus register from v2.20 upwards ( which i could find in the source code ), but i could not find the changes related to the Sensorbox, or the upgrade procedure to update the firmware on the Sensorbox.

Is it correct that i still need to update the Sensorbox firmware in order to have a working setup with v2.30+ ?

As an alternative solution i tried using the SolarEdge Sunspec configuration, but this is also not a viable solution for me as address needs to be between 10 and 247, while our ID is currently configured at 2 + we only have 3 dipswitches ( so i'm not even able to configure a number higher than 10 )

Thanks !

**Comment by kennyschuoler** [comment]
I also just tried connecting the SolarEdge SunSpec config, but there i also bump against the current fix; it's only possible to select the address starting from 10-247 ( while our ID is 2... )

**Comment by bobosch** [comment]
Hi,

do you have configured one SmartEVSE as Master an one as Node 1 ?
If the master detects other traffic on the RS485 bus it stops sending modbus request for 4 seconds
https://github.com/SmartEVSE/SmartEVSE-2/commit/1f0bc9ffe44c02f13dfd7752a36b76c7062dc0f0
The message "Another modbus master detected" should written to the console.
After 10 seconds the error message "no communication" appears..

If you like to query the devices via modbus, set the request interval > 30 seconds.

Robert

**Comment by kennyschuoler** [comment]
This seems to fix it indeed, thanks @bobosch !
