### ISSUE TITLE
Next release?

### ISSUE THREAD

**Issue by PA1RB** [SmartEVSE/Sensorbox-2#6]
As I am considering programming features to allow HomeAssistant to influence the charging process, I thought it might be worth to ask the question first: _is the next version under active development, with a release planned in the coming weeks/months?_

@mstegen wrote:
I'll release a version of the PIC firmware soon that will only do the CT measurements, and will not use the RS485 bus, nor use the P1 port. On this version the ESP32 will handle everything else.

**Comment by mstegen** [comment]
Yes, i'm actively working on both the next SmartEVSE v3 version as well as the Sensorbox 2 code.
Also adding a Wifi setup feature to the SmartESVE v2 code that allows you to connect the Sensorbox2 to the WiFi network.

**Comment by mstegen** [comment]
@PA1RB I've just updated the Sensorbox 2 code.
